//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModelo.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        public int Id { get; set; }
        public Nullable<int> pacienteID { get; set; }
        public Nullable<int> especialidadeID { get; set; }
        public Nullable<System.DateTime> dataConsulta { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
